language: ruby
rvm:
 - 2.2
 - jruby
sudo: require
services:
  - docker

before_install:
  - docker build -t moreno/testtravis -f Dockerfile.dev .
 

script:

  - docker run moreno/testtravis npm run test -- --coverage
