language: ruby

services:
  - docker

before_install:
  - docker build -t moreno/travis -f Dockerfile.dev
  - docker run -d -p 127.0.0.1:80:4567 moreno/travis /bin/sh -c "cd /root/Morris; bundle exec foreman start;"
  - docker ps -a
  - docker run moreno/travis /bin/sh -c "cd /root/Morris; bundle exec rake test"

script:
  - bundle exec rake test