language: node_js
node_js: node
cache: npm

sudo: required
services:
  - docker

before_install:
  - docker build -t moreno/travis -f Dockerfile.dev .

script:
  - docker run moreno/travis npm run test -- --coverage