language: ruby
rvm:
 - 2.2
 - jruby
sudo: true
services:
  - docker

before_install:
  - docker build -t moreno/testtravis -f Dockerfile.dev .
  - gem update --system
  - gem install bundler -v 1.16.1

 

script:

  - docker run moreno/testtravis npm run test -- --coverage
