services:
  - docker

before_install:
  - docker build -t moreno/testtravis -f Dockerfile.dev .
 - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"

script:

  - docker run moreno/testtravis npm run test -- --coverage
