sudo: require
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t moreno/testtravis -f Dockerfile.dev .
 

script:

  - docker run moreno/testtravis npm run test -- --coverage
